### ISSUE TITLE
Changing lane on one node breaks lane config on other node of same section

### ISSUE THREAD

**Issue by michaelberthold** [slyh/Cities2-TrafficLightsEnhancement#16] opened 2023-11-25 11:26 UTC
If a road between two intersections has only one segment and you try to change the lane arrow config on one end it will break the lane arrow config on the other end. In fact, the lane arrows will disappear completely and cars will use every lane in every direction.

Steps to reproduce
1. Build a four lane road (or more lanes)
2. Add an intersection
3. Add another intersection nearby (less than 200 meters)
4. Change lane arrows on one intersection
5. Look at other intersection

Workaround
Add a node between the intersections. You then get a strange texture at the node but the 2 intersections will be configurable as aexpected.

Screenshot
![Cities2-Various-Mods_LaneArrowBug](https://github.com/slyh/Cities2-Various-Mods/assets/38791666/80074aff-5582-4966-80df-b0f38ab5def7)

**Comment by slyh** [comment] 2023-11-25 17:32
Could you try the [latest release](https://github.com/slyh/Cities2-Various-Mods/releases/tag/2023.11.23-hotfix) and see if it works correctly?

**Comment by ColdCathode01** [comment] 2023-11-26 21:36
I had a similar problem in the latest release. I found that simply toggling the intersection with the missing arrows remedies it, at least temporarily.

**Comment by slyh** [comment] 2023-11-27 10:53
@ColdCathode01 I can’t reproduce it in 0.2.1-RC, could you share a screenshot of your road setup?

**Comment by DragonWin** [comment] 2023-11-27 13:55
Hi Slyh,

I just downloaded the 0.2.1-RC version, and I can reproduce the issue.

1. Start new game.
2. Create a grid, set all arrows to only allow traffic to their side (left lane = left turn only, right lane right turn only)
![lanes-setup-correctly](https://github.com/slyh/Cities2-Various-Mods/assets/992607/c9c14b58-05a4-413e-b3e3-8f6a4e020d17)

3. Add a new road between the two roads, and all lane settings are gone.
![Adding_road_removes_lane_settings](https://github.com/slyh/Cities2-Various-Mods/assets/992607/50208baf-8641-4e86-9b69-6774b341f9fc)

4. And just to throw it in there, mousing over an intersection with the tool open shows incorrect arrows
![mouse-over-shows-incorrect-arrows](https://github.com/slyh/Cities2-Various-Mods/assets/992607/a0e935b3-9571-441d-af4c-c428abed6503)

**Comment by ColdCathode01** [comment] 2023-11-27 18:52
> @ColdCathode01 I can’t reproduce it in 0.2.1-RC, could you share a screenshot of your road setup?

@slyh After ensuring my mod version was the latest version (which it appears it was not) I am not able to reproduce the issue that the OP was having. However the issue that @DragonWin is showing is still existing, where adding a node in anyway to a single segment of road (less then 200m) will cause the lane config for all adjacent intersections to set every lane to every direction.

This was my original test setup, segment between the intersections is 128m, no changes made, just the default settings made by the mod.
![27-November-10-22-51-00](https://github.com/slyh/Cities2-Various-Mods/assets/152103281/20bea45f-c67f-464e-9913-8c956c678db3)

Add a Ped Path with a cross walk (or another road as previously mentioned) and the two adjacent intersections now have all lanes set everywhere (including Uturns as shown by the path marking on the road). Though when I open the config for the intersections, none of the lanes are configured.
![27-November-10-27-29-01](https://github.com/slyh/Cities2-Various-Mods/assets/152103281/39a2aefd-1cbf-41c0-8248-6660dac24dfc)

This one is a mild frustration because I frequently use this ped path technique to add a node so I can have two opposing asymmetrical roads.

**Comment by slyh** [comment] 2023-11-27 19:59
I've reproduced the issue reported by @DragonWin. The bug stems from custom lane data being indexed according to their in-game geometry position. When road changes occur, the lane positions shift slightly, causing the custom data to no longer match.

I should have opted for a more robust lane-matching method. In the short term, I'll reduce the precision so they can match. In the long term, I need to find a more reliable matching method.

**Comment by slyh** [comment] 2023-11-30 02:53
Issues mentioned in this thread should be fixed in [v0.2.2-alpha](https://github.com/slyh/Cities2-Various-Mods/releases/tag/v0.2.2-alpha).

**Comment by ColdCathode01** [comment] 2023-11-30 06:00
> Issues mentioned in this thread should be fixed in [v0.2.2-alpha](https://github.com/slyh/Cities2-Various-Mods/releases/tag/v0.2.2-alpha).

The issue does seem to be mostly resolved with this Alpha version, it does still seem to happen when I add a road to an existing intersection that I already configured, but only to the road that I added, the rest of the intersection is unaffected. So definitely much less annoying and manageable.

Image for reference, the road on east side was added to the intersection after I had configured the lanes for the North, South and West roads. The existing roads updated nicely to accommodate the new road, however the new road just set its lanes to every direction, as you can see.
![29-November-21-45-03-00](https://github.com/slyh/Cities2-Various-Mods/assets/152103281/70ad1520-eb3f-4af2-87f1-5077915e73c9)

Overall though, it works great now, no more intersections at the other end of the road being changed unexpectedly. 
Many thanks and great work!

**Closed** 2023-12-10 14:03 UTC
Labels: good first issue
